sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t erwandupuis/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true erwandupuis/docker-react npm run test
